#!/bin/bash
#
sudo /home/pi/uvc-gadget/multi-gadget.sh
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c auto_exposure_bias=12
/usr/bin/v4l2-ctl -c video_bitrate=25000000
/usr/bin/v4l2-ctl -c white_balance_auto_preset=1
/usr/bin/v4l2-ctl -c iso_sensitivity_auto=1
/usr/bin/v4l2-ctl -c exposure_metering_mode=1
/usr/bin/v4l2-ctl -c contrast=5
/usr/bin/v4l2-ctl -c brightness=55
/usr/bin/v4l2-ctl -c saturation=-25
/usr/bin/v4l2-ctl -c sharpness=100
sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s2 -r1  -u /dev/video1 -v /dev/video0

