#!/bin/bash
#
sudo /home/pi/uvc-gadget/multi-gadget.sh
/usr/bin/v4l2-ctl -c auto_exposure=0
/usr/bin/v4l2-ctl -c video_bitrate=10000000
/usr/bin/v4l2-ctl -c width=1280
/usr/bin/v4l2-ctl -c height=720
sudo /home/pi/uvc-gadget/uvc-gadget -f1 -s2 -r1  -u /dev/video1 -v /dev/video0

